spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/currency_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:liquibase/changelog/changelog-master.yaml

scheduling:
  cron:
    fetch-exchange-rates: "0 0 * * * *"  # Every hour

integration:
  exchange-rate:
    url: http://apilayer.net/api/
    key: 7d49501a7c9f226b81b59835c1a2567e
    format: 1
